<a href="https://colab.research.google.com/github/victorchiea/MITxPro_Module_2/blob/main/Copy_of_Deep_Learning_Mastering_Neural_Networks_Module_2_Assignment_Wine_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 2 Assignment: Wine Classification

In this notebook we will revisit our binary classification problem, but this time we will be classifying a real world dataset!

The dataset we have chosen for this assignment is the wine quality dataset (https://archive.ics.uci.edu/ml/datasets/wine+quality). These datasets include information on over 6000 bottles of red and white wine. Your task is to develop a Single Neuron Classifier that can discern between white and red wine with a reasonable accuracy. We have provided code below for assistance with uploading the files and preparing the dataset (this is a good chance for you to learn more Python by example). Additionally we have included the final function calls we would like you to run to train and evaluate your classifier. Feel free to re-use code you have already written or seen in previous notebooks!

In [ ]:
# Download the wine .csv files from data archive
!rm -f winequality-red.csv winequality-white.csv
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv

--2022-02-01 16:44:14--  https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84199 (82K) [application/x-httpd-php]
Saving to: ‘winequality-red.csv’

winequality-red.csv 100%[===================>]  82.23K  --.-KB/s    in 0.1s

2022-02-01 16:44:15 (582 KB/s) - ‘winequality-red.csv’ saved [84199/84199]

--2022-02-01 16:44:15--  https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 264426 (258K) [application/x-httpd-php]
Saving to: ‘winequality-white.csv’

winequality-white.c 100%[===================>] 258.23K   941KB/s    in 0.3s

2022-02-01 16:44:15 (941 KB/s) - ‘winequality-white.csv’ saved [264426/264426]

In [ ]:
# These are the packages required for this assignment
import pandas as pd
import numpy as np

# Use Pandas to read the csv file into a dataframe.
# Note that the delimiter in this csv is the semicolon ";" instead of a ,
df_red = pd.read_csv('winequality-red.csv',delimiter=";")

# Because we are performing a classification task, we will assign all red wine a label of 1
df_red["color"] = 1

# The method .head() is super useful for seeing a preview of our data!
df_red.head()

   fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  color
0            7.4              0.70         0.00  ...      9.4        5      1
1            7.8              0.88         0.00  ...      9.8        5      1
2            7.8              0.76         0.04  ...      9.8        5      1
3           11.2              0.28         0.56  ...      9.8        6      1
4            7.4              0.70         0.00  ...      9.4        5      1

[5 rows x 13 columns]

In [ ]:
df_white = pd.read_csv('winequality-white.csv',delimiter=";")
df_white["color"] = 0  #assign white wine the label 0
df_white.head()

   fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  color
0            7.0              0.27         0.36  ...      8.8        6      0
1            6.3              0.30         0.34  ...      9.5        6      0
2            8.1              0.28         0.40  ...     10.1        6      0
3            7.2              0.23         0.32  ...      9.9        6      0
4            7.2              0.23         0.32  ...      9.9        6      0

[5 rows x 13 columns]

In [ ]:
# Now we combine our two dataframes
df = pd.concat([df_red, df_white])

# And shuffle them in place to mix the red and white wine data together
df = df.sample(frac=1).reset_index(drop=True)
df.head()

   fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  color
0            7.6              0.41         0.33  ...     11.2        5      1
1            5.7              0.26         0.27  ...      9.4        6      0
2            6.5              0.26         0.32  ...      9.5        6      0
3            5.8              0.36         0.38  ...     11.4        4      0
4            5.3              0.36         0.27  ...     11.6        6      0

[5 rows x 13 columns]

In [ ]:
# We choose three attributes of the wine to perform our prediction on
input_columns = ["citric acid", "residual sugar", "total sulfur dioxide"]
output_columns = ["color"]

# We extract the relevant features into our X and Y numpy arrays
X = df[input_columns].to_numpy()
Y = df[output_columns].to_numpy()
print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)
in_features = X.shape[1]

Shape of X: (6497, 3)
Shape of Y: (6497, 1)

In [ ]:
# Your Code Here!

# classification_model = ...

# train the model...
learning_rate = 0.001
epochs = 200
#...

# We will use this function to evaluate how well our trained classifier perfom
# Hint: the model you define above must have a .forward function in order to be compatible
# Hint: this evaluation function is identical to those in previous notebooks
def evaluate_classification_accuracy(model, input_data, labels):
    # Count the number of correctly classified samples given a set of weights
    correct = 0
    num_samples = len(input_data)
    for i in range(num_samples):
        x = input_data[i,...]
        y = labels[i]
        y_predicted = model.forward(x)
        label_predicted = 1 if y_predicted > 0.5 else 0
        if label_predicted == y:
            correct += 1
    accuracy = correct / num_samples
    print("Our model predicted", correct, "out of", num_samples,
          "correctly for", accuracy*100, "% accuracy")
    return accuracy